version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: turnosbd
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  appmic-turnosbackend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: appmic-turnosbackend
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: turnosbd
      DB_USER: root
      DB_PASS: root_password
    depends_on:
      - mysql
volumes:
  mysql-data: