server:
  port: 8080

spring:
  application:
    name: turnosbackend
  datasource:
    url: jdbc:mysql://localhost:3306/turnosbd?createDatabaseIfNotExist=true
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false